#Test

version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ia_database
    networks:
      - plataforma-ia
networks:
  plataforma-ia:

#Script: Docker compose up, correr test, docker compose down